### ISSUE TITLE
install script for ubuntu fails due to composer dependency [upgrade (2.0.0) double post]

### ISSUE THREAD

**Issue by eyebank** [passbolt/passbolt_install_scripts#13]
Here is the issue on fresh install on 10/24/2020

*************************
======================
Installing composer...
======================
--2020-10-24 17:08:55--  https://getcomposer.org/installer
Resolving getcomposer.org (getcomposer.org)... 142.44.245.229, 2607:5300:201:2100::4:d105
Connecting to getcomposer.org (getcomposer.org)|142.44.245.229|:443... connected                                  .
HTTP request sent, awaiting response... 200 OK
Length: 276190 (270K) [application/octet-stream]
Saving to: ‘composer-setup.php’

     0K .......... .......... .......... .......... .......... 18% 1.91M 0s
    50K .......... .......... .......... .......... .......... 37% 2.05M 0s
   100K .......... .......... .......... .......... .......... 55% 11.7M 0s
   150K .......... .......... .......... .......... .......... 74% 2.55M 0s
   200K .......... .......... .......... .......... .......... 92% 11.6M 0s
   250K .......... .........                                  100% 17.1M=0.08s

2020-10-24 17:08:55 (3.38 MB/s) - ‘composer-setup.php’ saved [276190/276190]

All settings correct for using Composer
Downloading...

Composer (version 2.0.0) successfully installed to: /usr/bin/composer.phar
Use it: php /usr/bin/composer.phar

===================================
Installing composer dependencies...
===================================
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - thadafinser/package-info is locked to version v1.0.0 and an update of this package was not requested.
    - thadafinser/package-info v1.0.0 requires composer-plugin-api ^1.0 -> found  composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - thadafinser/package-info v1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api [2.0.0] but it does not match the constraint.
    - thadafinser/user-agent-parser v2.0.0 requires thadafinser/package-info ^1.0 -> satisfiable by thadafinser/package-info[v1.0.0].
    - thadafinser/user-agent-parser is locked to version v2.0.0 and an update of this package was not requested.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
passbolt@pm:~$ thadafinser/package-info is locked to version v1.0.0 and an update of this package was not requested.
-bash: thadafinser/package-info: No such file or directory
passbolt@pm:~$ php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
passbolt@pm:~$
passbolt@pm:~$ All settings correct for using Composer
Installing composer dependencies...
===================================
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - thadafinser/package-info is locked to version v1.0.0 and an update of this package was not requested.
    - thadafinser/package-info v1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  
Problem 2
    - thadafinser/package-info v1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - thadafinser/user-agent-parser v2.0.0 requires thadafinser/package-info ^1.0 -> satisfiable by thadafinser/package-info[v1.0.0].
    - thadafinser/user-agent-parser is locked to version v2.0.0 and an update of this package was not requested.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
passbolt@pm:~$ thadafinser/package-info is locked to version v1.0.0 and an update of this package was not requested.

Command 'All' not found, did you mean:

  command 'dll' from deb brickos

Try: sudo apt install <deb name>

passbolt@pm:~$ Downloading...
Downloading...: command not found
passbolt@pm:~$
passbolt@pm:~$ Composer (version 2.0.0) successfully installed to: /usr/bin/composer.phar
-bash: syntax error near unexpected token `version'
passbolt@pm:~$ Use it: php /usr/bin/composer.phar

Command 'Use' not found, did you mean:

  command 'nse' from deb ns2
  command 'ase' from deb ase

Try: sudo apt install <deb name>

**Comment by stripthis** [comment]
Duplicate. https://github.com/passbolt/passbolt_help/issues/37
