### ISSUE TITLE
(Working) Ubuntu 20.04 lts

### ISSUE THREAD

**Issue by chrisjsimpson** [passbolt/passbolt_install_scripts#14]
These are the only required changes to get passbolt functionning on ubuntu 20.04. I hope someone finds it useful.

```
diff ./dist/ubuntu/passbolt_ce_ubuntu_installer.sh.old ./dist/ubuntu/passbolt_ce_ubuntu_installer.sh
< readonly FPM_WWW_POOL="/etc/php/7.2/fpm/pool.d/www.conf"
< readonly FPM_SERVICE="php7.2-fpm"
---
> readonly FPM_WWW_POOL="/etc/php/7.4/fpm/pool.d/www.conf"
> readonly FPM_SERVICE="php7.4-fpm"
```

**Comment by garrettboone** [comment]
Thank you for this @chrisjsimpson

**Comment by dlen** [comment]
Hi @chrisjsimpson,

Thanks for your submission. We really appreciate it! We have just published an ubuntu package so we will be deprecating the support for the install scripts on ubuntu. Check it out!

**Comment by chrisjsimpson** [comment]
Thanks for the heads up 🙂
