### ISSUE TITLE
Question: How to reinstall/remove Passbolt from Ubuntu

### ISSUE THREAD

**Issue by michaelhidalgo** [passbolt/passbolt_install_scripts#18]
Hey folks, I did a mistake during the setup of Passbolt, I tied to reinstall it by running the command again but the deployment is in an idle state and I need to reset the installation.

How can do this in a clean fashion? Is it possible to reinstall it and install it over?

Thanks.

**Comment by stripthis** [comment]
Hello,

Please post your question on the community forum, as github is used to report bugs only:
https://community.passbolt.com/

Best,
