### ISSUE TITLE
server_names_hash_bucket_size error

### ISSUE THREAD

**Issue by O1lpunch3r** [passbolt/passbolt_install_scripts#3]
Hello,

when installing Passbolt with these install_scripts then following nginx error occured:

`could not build the server_names_hash, you should increase server_names_hash_bucket_size`

These error could be avoided by setting the server_names_hash_bucket_size in nginx passbolt config to 64 or 128.

**Comment by dlen** [comment]
Hi there,

Thanks for your feedback! 
Just to clarify your use case is a long or large number of server names right?

**Comment by O1lpunch3r** [comment]
The server name is 21 characters long, so i think it is a normal use case when using one subdomain for adressing the Passbolt instance.

But it is enough to crash the default values of a nginx installation.
