### ISSUE TITLE
Centos: Firewall left unconfigured blocking access to passbolt interface.

### ISSUE THREAD

**Issue by BuildTheRobots** [passbolt/passbolt_install_scripts#6]
At the end of the CLI based installer, the user is told to go to the passbolt web interface, which is inaccessable.

Centos 7 ships with the firewall enabled as default and needs http/s services allowing through it.

There are arguments both for and against the installer doing this (it could easily be said that it's the system administrator's responsibility), I would argue that the installer should take care of it.

The installation process makes it very clear that it "will configure your operating system to be passbolt ready and will take care of installing and configuring the web server (Nginx), database (MariaDb), PHP, SSL and GPG keyring", which to me implies that it should "just work" afterwards.

This is at best, confusing to users as following the documented instructions isn't actually enough to get going. Ideally the installer should either prompt for firewall setup, or probably just do it - we don't prompt for nginx configuration and installation, and being able to access it after install seems like a logical part of it.

**Comment by pthoelken** [comment]
@dlen would do you solve this issue? Otherwise I can take a look into and make an pr after fix it?

**Comment by dlen** [comment]
Hi @pthoelken ,

I added some patch on develop I will try to merge this week.

Thanks for reminding me and sorry everyone in this thread waiting for so long.
