### ISSUE TITLE
Setting up mariadb... > ERROR 1064 (42000) at line 7: You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by kuerious** [passbolt/passbolt_install_scripts#9]
System:
ESXi 6.7 VM, Debian 9 x64 with full updates, ntpdate configured, security auto-updates configured

Attempt:
Installing Passbolt using installation script

Expectation:
Passbolt installer on **clean** Debian 9 install would function as described.

Result:
The script failed at the following code:

`Processing triggers for systemd (232-25+deb9u11) ...`
`=====================`
`Setting up mariadb...`
`=====================`
`ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that` `corresponds to your MariaDB server version for the right syntax to use near '-user@'localhost'` `identified by xxxxxxxxx at line 1`
`root@passwords:~#`

**Comment by dlen** [comment]
Thanks for the report looks like backticks are missing on the mysql installation that is why you face this error.
I will try to fix this soon as there is some work scheduled to revamp the scripts for debian 10.

**Comment by kuerious** [comment]
Can I do anything in the meantime? Manually?

**Comment by dlen** [comment]
Hi, 

Yes you can patch it manually, it's pretty easy fix.

Edit passbolt_pro_debian_installer.sh

Go to line 683 and replace the whole line with the following one:

```
CREATE DATABASE IF NOT EXISTS \`$(__config_get "$_config_db")\`;
```
Go to line 684 and proceed the same with the following:
```
GRANT ALL ON \`$(__config_get "$_config_db")\`.* to \`$(__config_get "$_config_user")\`@'localhost' identified by '$(__config_get "$_config_pw")';
```

**Comment by kuerious** [comment]
Like this:

[image: image.png]

https://i.imgur.com/rvXS1j4.png

**Comment by kuerious** [comment]
Now I'm getting a new error, in trying to setup "let's encrypt":

[image: image.png]

https://i.imgur.com/CVzM9zc.png

**Comment by kuerious** [comment]
NM. Seems I need to use my public info for a public Let's Encrypt. Not your
issue.

https://community.letsencrypt.org/t/name-does-not-end-in-a-public-suffix/77293/3

**Comment by kuerious** [comment]
Or like this:

[image: image.png]

https://i.imgur.com/fHsRf0K.png

**Comment by dlen** [comment]
This one looks good: https://i.imgur.com/fHsRf0K.png
